"""
Manual PTX patch for CuTe DSL TMA kernel: replace shared::cluster with shared::cta.

Same methodology as triton/tma_manual_patch.py:
  1. Compile CuTe DSL kernel (generates PTX into cute_cache/)
  2. Locate the generated PTX
  3. String-replace cluster->cta
  4. ptxas -> cubin
  5. Load via raw CUDA driver API
  6. Verify no ~3.7 GiB allocation and no __cuda_syscall_* symbols

Note: CuTe DSL kernel arguments are auto-generated by the compiler; raw
launcher parameter packing is non-trivial. We verify up to cuModuleLoadData
+ cuModuleGetFunction + SASS/ELF scan, which is sufficient to prove the
patch removes the leak root-cause.

Usage:
  python sm120_tma_mem_blackhole/cutedsl/tma_manual_patch.py
"""

import ctypes
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import torch

# --------------------------------------------------------------------------- #
# CuTe DSL env setup (must happen before import cutlass)
# --------------------------------------------------------------------------- #
_CACHE = Path(__file__).parent / "cute_cache"
_CACHE.mkdir(exist_ok=True)
os.environ.setdefault("CUTE_DSL_CACHE_DIR", str(_CACHE / "mlir_cache"))
os.environ.setdefault("CUTE_DSL_DUMP_DIR", str(_CACHE))
if "CUTE_DSL_ARCH" not in os.environ:
    mj, mn = torch.cuda.get_device_capability(0)
    os.environ["CUTE_DSL_ARCH"] = f"sm_{mj}{mn}"

import cutlass
import cutlass.cute as cute
import cutlass.utils as utils
from cutlass.cute.runtime import from_dlpack
from cutlass.cute.nvgpu import cpasync

from common.cuda_utils import warmup_cuda_context
from common.cuda_utils import resolve_cuobjdump
from common.mem_utils import fmt_gb, nvml_init, nvml_used

TILE_M = 128
TILE_N = 128


class _TmaIdentityCopy:
    @cute.jit
    def __call__(self, mA, mB):
        self.dtype = mA.element_type
        tile = (TILE_M, TILE_N)
        smem_layout = cute.make_ordered_layout(tile, order=(1, 0))

        tma_load_atom, tma_gA = cpasync.make_tiled_tma_atom(
            cpasync.CopyBulkTensorTileG2SOp(), mA, smem_layout, tile,
        )
        tma_store_atom, tma_gB = cpasync.make_tiled_tma_atom(
            cpasync.CopyBulkTensorTileS2GOp(), mB, smem_layout, tile,
        )

        M = cute.size(mA, mode=[0])
        N = cute.size(mA, mode=[1])
        grid = (
            (M + TILE_M - 1) // TILE_M,
            (N + TILE_N - 1) // TILE_N,
            1,
        )

        self.kernel(
            tma_load_atom, tma_gA,
            tma_store_atom, tma_gB,
            smem_layout,
        ).launch(grid=grid, block=[128, 1, 1])

    @cute.kernel
    def kernel(
        self,
        tma_load_atom, tma_gA,
        tma_store_atom, tma_gB,
        smem_layout,
    ):
        bidx, bidy, _ = cute.arch.block_idx()
        tidx, _, _ = cute.arch.thread_idx()

        smem = utils.SmemAllocator()
        sA = smem.allocate_tensor(self.dtype, smem_layout, byte_alignment=128)
        mbar_ptr = smem.allocate_array(cutlass.Int64, num_elems=1)

        gA_tiled = cute.flat_divide(tma_gA, (TILE_M, TILE_N))
        gB_tiled = cute.flat_divide(tma_gB, (TILE_M, TILE_N))

        bSG_sA, bSG_gA = cpasync.tma_partition(
            tma_load_atom, 0, cute.make_layout(1),
            cute.group_modes(sA, 0, cute.rank(sA)),
            cute.group_modes(gA_tiled, 0, 2),
        )
        bSG_sB, bSG_gB = cpasync.tma_partition(
            tma_store_atom, 0, cute.make_layout(1),
            cute.group_modes(sA, 0, cute.rank(sA)),
            cute.group_modes(gB_tiled, 0, 2),
        )

        tile_bytes = cute.size_in_bytes(self.dtype, smem_layout)

        if tidx == 0:
            cute.arch.mbarrier_init(mbar_ptr, 1)
        cute.arch.mbarrier_init_fence()
        cute.arch.sync_threads()

        if tidx == 0:
            cute.arch.mbarrier_arrive_and_expect_tx(mbar_ptr, tile_bytes)
            cute.copy(
                tma_load_atom,
                bSG_gA[(None, bidx, bidy)],
                bSG_sA[(None,)],
                tma_bar_ptr=mbar_ptr,
            )
        cute.arch.mbarrier_wait(mbar_ptr, phase=0)

        cute.arch.fence_view_async_shared()
        cute.arch.sync_threads()

        if tidx == 0:
            cute.copy(
                tma_store_atom,
                bSG_sB[(None,)],
                bSG_gB[(None, bidx, bidy)],
            )
            cute.arch.cp_async_bulk_commit_group()
            cute.arch.cp_async_bulk_wait_group(0, read=False)


# --------------------------------------------------------------------------- #
# PTX helpers
# --------------------------------------------------------------------------- #
def _find_latest_ptx(cache_dir: Path) -> Path:
    """Return the most recently modified .ptx under cache_dir."""
    ptx_files = list(cache_dir.rglob("*.ptx"))
    if not ptx_files:
        raise RuntimeError(f"No .ptx found under {cache_dir}")
    return max(ptx_files, key=lambda p: p.stat().st_mtime)


def _parse_kernel_name(ptx_text: str) -> str:
    m = re.search(r"\.visible\s+\.entry\s+(\w+)\s*\(", ptx_text)
    if not m:
        raise RuntimeError("Cannot find kernel entry point in PTX")
    return m.group(1)


def _parse_target(ptx_text: str) -> str:
    m = re.search(r"\.target\s+(sm_\d+)", ptx_text)
    if not m:
        raise RuntimeError("Cannot find .target directive in PTX")
    return m.group(1)


def _find_ptxas(arch: str) -> str:
    from triton.backends.nvidia.compiler import get_ptxas
    m = re.match(r"sm_(\d+)", arch)
    arch_num = int(m.group(1)) if m else 80
    return get_ptxas(arch_num).path


def _ptxas_to_cubin(ptx_text: str, arch: str) -> bytes:
    ptxas = _find_ptxas(arch)
    with tempfile.NamedTemporaryFile(suffix=".ptx", mode="w", delete=False) as f:
        f.write(ptx_text)
        ptx_path = f.name
    cubin_path = ptx_path.replace(".ptx", ".cubin")
    try:
        subprocess.run(
            [ptxas, f"-arch={arch}", ptx_path, "-o", cubin_path],
            check=True, capture_output=True, text=True,
        )
        with open(cubin_path, "rb") as f:
            return f.read()
    finally:
        os.unlink(ptx_path)
        if os.path.exists(cubin_path):
            os.unlink(cubin_path)


def main():
    warmup_cuda_context()
    handle = nvml_init(torch.cuda.current_device())

    nvml_before = nvml_used(handle)
    print(f"[CuTeDSL-ManualPatch][nvml] BEFORE any alloc: {fmt_gb(nvml_before)}")

    # 1. Compile (do not launch — livelocks on SM120).
    a = torch.randn((TILE_M, TILE_N), dtype=torch.bfloat16, device="cuda")
    b = torch.empty_like(a)
    a_ct = from_dlpack(a).mark_layout_dynamic(leading_dim=1)
    b_ct = from_dlpack(b).mark_layout_dynamic(leading_dim=1)

    copy = _TmaIdentityCopy()
    compiled = cute.compile(copy, a_ct, b_ct)
    torch.cuda.synchronize()
    print("  [CuTeDSL] compile: OK")

    nvml_after_compile = nvml_used(handle)
    print(f"[CuTeDSL-ManualPatch][nvml] after compile: {fmt_gb(nvml_after_compile)} "
          f"(d={fmt_gb(nvml_after_compile - nvml_before)})")

    # 2. Locate generated PTX.
    ptx_file = _find_latest_ptx(_CACHE)
    print(f"  [CuTeDSL] PTX: {ptx_file.name}")
    ptx = ptx_file.read_text()

    # 3. Patch.
    NEEDLE = "cp.async.bulk.tensor.2d.shared::cluster.global"
    REPLACE = "cp.async.bulk.tensor.2d.shared::cta.global"
    assert NEEDLE in ptx, "PTX does not contain shared::cluster — nothing to patch"
    ptx_patched = ptx.replace(NEEDLE, REPLACE)
    print("  [CuTeDSL] PTX patched (cluster -> cta)")

    # 4. ptxas.
    arch = _parse_target(ptx_patched)
    kernel_name = _parse_kernel_name(ptx_patched)
    cubin = _ptxas_to_cubin(ptx_patched, arch)
    print(f"  [CuTeDSL] ptxas -> cubin ({len(cubin)} bytes)")

    # 5. Raw driver load.
    libcuda = ctypes.CDLL("libcuda.so.1")
    module = ctypes.c_void_p()
    err = libcuda.cuModuleLoadData(ctypes.byref(module), cubin)
    assert err == 0, f"cuModuleLoadData failed: {err}"

    nvml_after_load = nvml_used(handle)
    print(f"[CuTeDSL-ManualPatch][nvml] after cuModuleLoadData: {fmt_gb(nvml_after_load)} "
          f"(d={fmt_gb(nvml_after_load - nvml_after_compile)})")

    # 6. Resolve function.
    func = ctypes.c_void_p()
    err = libcuda.cuModuleGetFunction(ctypes.byref(func), module, kernel_name.encode())
    assert err == 0, f"cuModuleGetFunction failed: {err}"
    print(f"  [CuTeDSL] function resolved: {kernel_name[:60]}...")

    # 7. ELF + SASS scan.
    cuobjdump = resolve_cuobjdump()
    with tempfile.NamedTemporaryFile(suffix=".cubin", delete=False) as f:
        f.write(cubin)
        cubin_path = f.name
    try:
        # ELF symbols
        out = subprocess.check_output(
            [cuobjdump, "--dump-elf-symbols", cubin_path],
            stderr=subprocess.STDOUT,
        ).decode("utf-8", errors="replace")
        syscalls = [ln for ln in out.splitlines() if "cuda_syscall" in ln]
        if syscalls:
            print(f"  [CuTeDSL] WARNING: still has {len(syscalls)} syscall ref(s)")
        else:
            print("  [CuTeDSL] cubin clean: no __cuda_syscall_* symbols")

        # SASS
        out = subprocess.check_output(
            [cuobjdump, "--dump-sass", cubin_path],
            stderr=subprocess.STDOUT,
        ).decode("utf-8", errors="replace")
        utmal = sum(1 for ln in out.splitlines() if "UTMALDG.2D" in ln)
        calls = sum(1 for ln in out.splitlines() if "CALL.ABS.NOINC" in ln)
        print(f"  [CuTeDSL] SASS UTMALDG.2D count: {utmal}")
        print(f"  [CuTeDSL] SASS CALL.ABS.NOINC count: {calls}")
    finally:
        os.unlink(cubin_path)

    # 8. Summary.
    delta_load = nvml_after_load - nvml_after_compile
    print(f"\n[CuTeDSL-ManualPatch] Black hole jump (load - compile): "
          f"{fmt_gb(delta_load)}")
    if delta_load < 200 * 1024 * 1024 and not syscalls and utmal > 0:
        print("=== PASS: patched cubin has no leak and uses inline UTMALDG.2D ===")
    else:
        print("=== FAIL or INCONCLUSIVE ===")


if __name__ == "__main__":
    main()
